
server:
  port: 8083
  
spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
      path: /h2-console 
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
 
logging:
  level:
    org.springframework.security: TRACE
    
management:
  endpoint:    health:      enabled: true
    
feign:  hystrix:    enabled: true
    